services:
  - type: web
    name: e-cuti
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e_cuti_db
          property: connectionString
      - key: SENDGRID_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CALENDAR_CREDENTIALS
        sync: false
databases:
  - name: e_cuti_db
    databaseName: e_cuti
    user: e_cuti_admin