"""Add alamat field to users table

Revision ID: 082553a87071
Revises: 
Create Date: 2025-05-09 12:49:04.522970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082553a87071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alamat', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('alamat')

    # ### end Alembic commands ###
