"""add profil

Revision ID: 1b81b783f986
Revises: fb37707065ac
Create Date: 2025-05-09 18:49:36.432079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b81b783f986'
down_revision = 'fb37707065ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuti', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
