"""Add lampiran

Revision ID: 25b3f24da958
Revises: 9f7298e8396f
Create Date: 2025-04-13 19:25:31.545307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b3f24da958'
down_revision = '9f7298e8396f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lampiran', sa.String(length=255), nullable=True))
        batch_op.alter_column('tanggal_mulai',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('tanggal_selesai',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('cancelled_at',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuti', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('cancelled_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tanggal_selesai',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('tanggal_mulai',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('lampiran')

    # ### end Alembic commands ###
