"""Create audit_logs table

Revision ID: 68c0c3f08f71
Revises: 6eecdbefab67
Create Date: 2025-05-10 21:28:34.733856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '68c0c3f08f71'
down_revision = '6eecdbefab67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('model_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('new_values')
        batch_op.drop_column('record_id')
        batch_op.drop_column('table_name')
        batch_op.drop_column('old_values')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_values', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('table_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('record_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('new_values', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.TEXT(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('model_id')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
