"""akun admin

Revision ID: 6e119ebe8b95
Revises: cdf8ab2f39e3
Create Date: 2025-05-11 01:25:13.902832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e119ebe8b95'
down_revision = 'cdf8ab2f39e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deactivated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deactivated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        
        # Tambahkan nama constraint yang unik
        batch_op.create_foreign_key(
            'fk_users_deleted_by',  # Nama constraint
            'users', 
            ['deleted_by'], 
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_users_deactivated_by',  # Nama constraint
            'users', 
            ['deactivated_by'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Hapus constraint dengan nama yang sesuai
        batch_op.drop_constraint('fk_users_deleted_by', type_='foreignkey')
        batch_op.drop_constraint('fk_users_deactivated_by', type_='foreignkey')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deactivated_by')
        batch_op.drop_column('deactivated_at')
    # ### end Alembic commands ###
