"""update user model

Revision ID: 716542f0c8c2
Revises: 25b3f24da958
Create Date: 2025-04-14 18:39:03.696060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716542f0c8c2'
down_revision = '25b3f24da958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('cuti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atasan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['atasan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuti', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('atasan_id')

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nip', sa.VARCHAR(length=100), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True),
    sa.Column('must_change_password', sa.BOOLEAN(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('tempat_lahir', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.VARCHAR(length=100), nullable=True),
    sa.Column('jenis_kelamin', sa.VARCHAR(length=9), nullable=True),
    sa.Column('golongan', sa.VARCHAR(length=50), nullable=True),
    sa.Column('jabatan', sa.VARCHAR(length=100), nullable=True),
    sa.Column('foto_profil', sa.VARCHAR(length=255), nullable=True),
    sa.Column('role', sa.VARCHAR(length=7), nullable=True),
    sa.Column('atasan_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('total_cuti', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['atasan_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nip'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
