"""add kepegawaian

Revision ID: fb37707065ac
Revises: 082553a87071
Create Date: 2025-05-09 13:31:47.870452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb37707065ac'
down_revision = '082553a87071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_nip')
        batch_op.create_unique_constraint(None, ['nip'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_nip', ['nip'], unique=1)

    # ### end Alembic commands ###
